2017-08-24T11:18:44.4497823+08:00  [FTL] Unable to start Kestrel. (fc6a528d)
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4092 EACCES permission denied
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.Bind(IPEndPoint endPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.ListenTcp(Boolean useFileHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.<>c.<StartAsync>b__8_0(Listener listener)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.CallbackAdapter`1.<>c.<.cctor>b__3_1(Object callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.DoPostWork()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.<StartAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAddressAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
2017-08-24T11:19:00.8453704+08:00 0HL7AJRE3TNR8:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T11:19:00.8890469+08:00 0HL7AJRE3TNR8:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T11:19:00.9122935+08:00 0HL7AJRE3TNR8:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T11:19:01.5988961+08:00 0HL7AJRE3TNR8:00000001 [INF] Request finished in 787.0152ms 404  (791a596a)
2017-08-24T11:19:11.9746902+08:00 0HL7AJRE3TNR8:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T11:19:12.0003852+08:00 0HL7AJRE3TNR8:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T11:19:12.0061126+08:00 0HL7AJRE3TNR8:00000002 [INF] User RequestPath：/ (2d52e501)
2017-08-24T11:19:12.0322294+08:00 0HL7AJRE3TNR8:00000002 [INF] Request finished in 38.4235ms 404  (791a596a)
2017-08-24T11:19:12.0585258+08:00 0HL7AJRE3TNR8:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T11:19:12.0680972+08:00 0HL7AJRE3TNR8:00000003 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T11:19:12.0804422+08:00 0HL7AJRE3TNR8:00000003 [INF] Request finished in 39.4879ms 200 image/x-icon (791a596a)
2017-08-24T11:19:32.8926775+08:00 0HL7AJRE3TNR8:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T11:19:32.9175246+08:00 0HL7AJRE3TNR8:00000004 [INF] User IP:::1 (2144b813)
2017-08-24T11:19:32.9637374+08:00 0HL7AJRE3TNR8:00000004 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T11:19:33.0440136+08:00 0HL7AJRE3TNR8:00000004 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T11:19:35.1313293+08:00 0HL7AJRE3TNR8:00000004 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 2098.6777ms (afa2e885)
2017-08-24T11:19:35.2641898+08:00 0HL7AJRE3TNR8:00000004 [ERR] Connection id ""0HL7AJRE3TNR8"", Request id ""0HL7AJRE3TNR8:00000004"": An unhandled exception was thrown by the application. (560e7d32)
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Views\_ViewImports.cshtml(1,7): error CS0246: The type or namespace name 'WebApplication1' could not be found (are you missing a using directive or an assembly reference?)
D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Views\_ViewImports.cshtml(2,7): error CS0246: The type or namespace name 'WebApplication1' could not be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T11:19:35.2687284+08:00 0HL7AJRE3TNR8:00000004 [INF] Request finished in 2399.1447ms 500  (791a596a)
2017-08-24T11:19:48.8822817+08:00 0HL7AJRE3TNR8:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T11:19:48.9072243+08:00 0HL7AJRE3TNR8:00000005 [INF] User IP:::1 (2144b813)
2017-08-24T11:19:48.9117771+08:00 0HL7AJRE3TNR8:00000005 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T11:19:48.9165904+08:00 0HL7AJRE3TNR8:00000005 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T11:20:10.6239441+08:00  [WRN] Heartbeat took longer than "00:00:01" at "08/24/2017 03:19:52 +00:00". (439152bf)
2017-08-24T11:20:23.2837280+08:00 0HL7AJRE3TNR8:00000005 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 34368.0527ms (afa2e885)
2017-08-24T11:20:29.6197699+08:00 0HL7AJRE3TNR8:00000005 [ERR] Connection id ""0HL7AJRE3TNR8"", Request id ""0HL7AJRE3TNR8:00000005"": An unhandled exception was thrown by the application. (560e7d32)
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Views\_ViewImports.cshtml(1,7): error CS0246: The type or namespace name 'WebApplication1' could not be found (are you missing a using directive or an assembly reference?)
D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Views\_ViewImports.cshtml(2,7): error CS0246: The type or namespace name 'WebApplication1' could not be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T11:20:29.6383318+08:00 0HL7AJRE3TNR8:00000005 [INF] Request finished in 40743.8138ms 500  (791a596a)
2017-08-24T11:21:48.8585995+08:00 0HL7AJRE3TNRM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T11:21:48.8649901+08:00 0HL7AJRE3TNRM:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T11:21:48.8901326+08:00 0HL7AJRE3TNRM:00000001 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T11:21:48.8965463+08:00 0HL7AJRE3TNRM:00000001 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T11:21:53.0704011+08:00 0HL7AJRE3TNRM:00000001 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T11:21:53.5373373+08:00 0HL7AJRE3TNRM:00000001 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 4637.929ms (afa2e885)
2017-08-24T11:21:53.6021152+08:00 0HL7AJRE3TNRM:00000001 [ERR] Connection id ""0HL7AJRE3TNRM"", Request id ""0HL7AJRE3TNRM:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'HeaderContent'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T11:21:53.6233108+08:00 0HL7AJRE3TNRM:00000001 [INF] Request finished in 4750.5929ms 500  (791a596a)
2017-08-24T11:21:53.6480752+08:00 0HL7AJRE3TNRM:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T11:21:53.6722551+08:00 0HL7AJRE3TNRM:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T11:21:53.6792604+08:00 0HL7AJRE3TNRM:00000002 [INF] Request finished in 30.7719ms 200 image/x-icon (791a596a)
2017-08-24T11:22:16.6114097+08:00 0HL7AJT8M3R93:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T11:22:16.6539719+08:00 0HL7AJT8M3R93:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T11:22:16.6775150+08:00 0HL7AJT8M3R93:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T11:22:16.8036908+08:00 0HL7AJT8M3R93:00000001 [INF] Request finished in 214.275ms 404  (791a596a)
2017-08-24T11:22:48.9808433+08:00 0HL7AJT8M3R93:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T11:22:48.9881760+08:00 0HL7AJT8M3R93:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T11:22:49.0141631+08:00 0HL7AJT8M3R93:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T11:22:49.0766236+08:00 0HL7AJT8M3R93:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T11:22:56.2263056+08:00 0HL7AJT8M3R93:00000002 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T11:22:56.6425770+08:00 0HL7AJT8M3R93:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 7575.0228ms (afa2e885)
2017-08-24T11:22:56.7445084+08:00 0HL7AJT8M3R93:00000002 [ERR] Connection id ""0HL7AJT8M3R93"", Request id ""0HL7AJT8M3R93:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'HeaderContent'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T11:22:56.7612458+08:00 0HL7AJT8M3R93:00000002 [INF] Request finished in 7771.2676ms 500  (791a596a)
2017-08-24T12:39:19.7221291+08:00 0HL7AL8AFDS5L:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T12:39:19.7666793+08:00 0HL7AL8AFDS5L:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T12:39:19.7758627+08:00 0HL7AL8AFDS5L:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T12:39:19.9223812+08:00 0HL7AL8AFDS5L:00000001 [INF] Request finished in 209.4727ms 404  (791a596a)
2017-08-24T12:39:27.5494399+08:00 0HL7AL8AFDS5L:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:39:27.5758074+08:00 0HL7AL8AFDS5L:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T12:39:27.5810860+08:00 0HL7AL8AFDS5L:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:39:27.6415937+08:00 0HL7AL8AFDS5L:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T12:39:33.3682150+08:00 0HL7AL8AFDS5L:00000002 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T12:39:33.7794448+08:00 0HL7AL8AFDS5L:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 6147.4466ms (afa2e885)
2017-08-24T12:39:33.8872568+08:00 0HL7AL8AFDS5L:00000002 [ERR] Connection id ""0HL7AL8AFDS5L"", Request id ""0HL7AL8AFDS5L:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'HeaderContent'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T12:39:33.8971260+08:00 0HL7AL8AFDS5L:00000002 [INF] Request finished in 6346.6345ms 500  (791a596a)
2017-08-24T12:40:20.8193368+08:00 0HL7AL8AFDS5L:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:40:20.8330557+08:00 0HL7AL8AFDS5L:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T12:40:20.8640740+08:00 0HL7AL8AFDS5L:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:40:20.8717028+08:00 0HL7AL8AFDS5L:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T12:40:22.6814453+08:00 0HL7AL8AFDS5L:00000003 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T12:40:22.7173696+08:00 0HL7AL8AFDS5L:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1848.2454ms (afa2e885)
2017-08-24T12:40:22.7731428+08:00 0HL7AL8AFDS5L:00000003 [ERR] Connection id ""0HL7AL8AFDS5L"", Request id ""0HL7AL8AFDS5L:00000003"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'HeaderContent'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T12:40:22.7843288+08:00 0HL7AL8AFDS5L:00000003 [INF] Request finished in 1965.8466ms 500  (791a596a)
2017-08-24T12:40:22.8044414+08:00 0HL7AL8AFDS5L:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T12:40:22.8099537+08:00 0HL7AL8AFDS5L:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T12:40:22.8204389+08:00 0HL7AL8AFDS5L:00000004 [INF] Request finished in 15.9035ms 200 image/x-icon (791a596a)
2017-08-24T12:40:30.9203813+08:00 0HL7AL8AFDS5L:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:40:30.9504133+08:00 0HL7AL8AFDS5L:00000005 [INF] User IP:::1 (2144b813)
2017-08-24T12:40:30.9559092+08:00 0HL7AL8AFDS5L:00000005 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:40:30.9619318+08:00 0HL7AL8AFDS5L:00000005 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T12:40:32.7482284+08:00 0HL7AL8AFDS5L:00000005 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T12:40:32.7560074+08:00 0HL7AL8AFDS5L:00000005 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1795.6463ms (afa2e885)
2017-08-24T12:40:32.8242999+08:00 0HL7AL8AFDS5L:00000005 [ERR] Connection id ""0HL7AL8AFDS5L"", Request id ""0HL7AL8AFDS5L:00000005"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'HeaderContent'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T12:40:32.8417005+08:00 0HL7AL8AFDS5L:00000005 [INF] Request finished in 1912.2409ms 500  (791a596a)
2017-08-24T12:40:32.8643162+08:00 0HL7AL8AFDS5L:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T12:40:32.8698414+08:00 0HL7AL8AFDS5L:00000006 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T12:40:32.8764698+08:00 0HL7AL8AFDS5L:00000006 [INF] Request finished in 9.8711ms 200 image/x-icon (791a596a)
2017-08-24T12:41:16.8248847+08:00 0HL7AL8AFDS5L:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:41:16.8489155+08:00 0HL7AL8AFDS5L:00000007 [INF] User IP:::1 (2144b813)
2017-08-24T12:41:16.8733023+08:00 0HL7AL8AFDS5L:00000007 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:41:16.8982668+08:00 0HL7AL8AFDS5L:00000007 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T12:41:18.7359321+08:00 0HL7AL8AFDS5L:00000007 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T12:41:18.8568012+08:00 0HL7AL8AFDS5O:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/js/menu.js   (ca22a1cb)
2017-08-24T12:41:18.8804258+08:00 0HL7AL8AFDS5M:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/lib/bootstrap/dist/css/bootstrap.css   (ca22a1cb)
2017-08-24T12:41:18.8824355+08:00 0HL7AL8AFDS5N:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/css/site.css   (ca22a1cb)
2017-08-24T12:41:18.9301341+08:00 0HL7AL8AFDS5O:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T12:41:18.9324135+08:00 0HL7AL8AFDS5M:00000001 [INF] Sending file. Request path: '"/lib/bootstrap/dist/css/bootstrap.css"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\lib\bootstrap\dist\css\bootstrap.css"' (27b0a520)
2017-08-24T12:41:18.9572550+08:00 0HL7AL8AFDS5L:00000007 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1913.0631ms (afa2e885)
2017-08-24T12:41:18.9874777+08:00 0HL7AL8AFDS5N:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\css\site.css"' (27b0a520)
2017-08-24T12:41:19.0107339+08:00 0HL7AL8AFDS5L:00000007 [INF] Request finished in 2150.2434ms 200 text/html; charset=utf-8 (791a596a)
2017-08-24T12:41:19.0696611+08:00 0HL7AL8AFDS5N:00000001 [INF] Request finished in 225.6136ms 200 text/css (791a596a)
2017-08-24T12:41:19.0919661+08:00 0HL7AL8AFDS5O:00000001 [INF] User RequestPath：/menu/js/menu.js (aaba8f86)
2017-08-24T12:41:19.0998367+08:00 0HL7AL8AFDS5O:00000001 [INF] Request finished in 307.1678ms 404  (791a596a)
2017-08-24T12:41:19.1304466+08:00 0HL7AL8AFDS5O:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/lib/jquery/dist/jquery.js   (ca22a1cb)
2017-08-24T12:41:19.1355070+08:00 0HL7AL8AFDS5O:00000002 [INF] Sending file. Request path: '"/lib/jquery/dist/jquery.js"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\lib\jquery\dist\jquery.js"' (27b0a520)
2017-08-24T12:41:19.1582275+08:00 0HL7AL8AFDS5M:00000001 [INF] Request finished in 352.3029ms 200 text/css (791a596a)
2017-08-24T12:41:19.2090486+08:00 0HL7AL8AFDS5M:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/lib/bootstrap/dist/js/bootstrap.js   (ca22a1cb)
2017-08-24T12:41:19.2603795+08:00 0HL7AL8AFDS5L:00000008 [INF] Request starting HTTP/1.1 GET http://localhost:52141/images/v2/menu-up.png   (ca22a1cb)
2017-08-24T12:41:19.2960697+08:00 0HL7AL8AFDS5L:00000008 [INF] User IP:::1 (2144b813)
2017-08-24T12:41:19.3624578+08:00 0HL7AL8AFDS5N:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/js/site.js?v=7mkNbU1tgQL1bUeZe3j2R151hKLhLDKO4BBaR-iqCy0   (ca22a1cb)
2017-08-24T12:41:19.4727212+08:00 0HL7AL8AFDS5L:00000008 [INF] User RequestPath：/images/v2/menu-up.png (c0a44d72)
2017-08-24T12:41:19.4938303+08:00 0HL7AL8AFDS5M:00000002 [INF] Sending file. Request path: '"/lib/bootstrap/dist/js/bootstrap.js"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\lib\bootstrap\dist\js\bootstrap.js"' (27b0a520)
2017-08-24T12:41:19.5406159+08:00 0HL7AL8AFDS5L:00000008 [INF] Request finished in 330.2807ms 404  (791a596a)
2017-08-24T12:41:19.5502793+08:00 0HL7AL8AFDS5N:00000002 [INF] Sending file. Request path: '"/js/site.js"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\js\site.js"' (27b0a520)
2017-08-24T12:41:19.5858811+08:00 0HL7AL8AFDS5N:00000002 [INF] Request finished in 410.6011ms 200 application/javascript (791a596a)
2017-08-24T12:41:19.5873633+08:00 0HL7AL8AFDS5O:00000002 [INF] Request finished in 113.5306ms 200 application/javascript (791a596a)
2017-08-24T12:41:19.6205171+08:00 0HL7AL8AFDS5N:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T12:41:19.6468781+08:00 0HL7AL8AFDS5M:00000002 [INF] Request finished in 338.2767ms 200 application/javascript (791a596a)
2017-08-24T12:41:19.6695823+08:00 0HL7AL8AFDS5N:00000003 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T12:41:19.6948588+08:00 0HL7AL8AFDS5N:00000003 [INF] Request finished in 56.6444ms 200 image/x-icon (791a596a)
2017-08-24T12:43:15.5458998+08:00 0HL7AL8AFDS5N:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:43:15.5719285+08:00 0HL7AL8AFDS5N:00000004 [INF] User IP:::1 (2144b813)
2017-08-24T12:43:15.5969777+08:00 0HL7AL8AFDS5N:00000004 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:43:15.6232090+08:00 0HL7AL8AFDS5N:00000004 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T12:43:17.1912195+08:00 0HL7AL8AFDS5N:00000004 [INF] Executing ViewResult, running view at path "/Views/Menu/Index.cshtml". (9707eebe)
2017-08-24T12:43:17.4015736+08:00 0HL7AL8AFDS5N:00000004 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1798.9854ms (afa2e885)
2017-08-24T12:43:17.4252770+08:00 0HL7AL8AFDS5N:00000004 [INF] Request finished in 1862.412ms 200 text/html; charset=utf-8 (791a596a)
2017-08-24T12:43:17.4478538+08:00 0HL7AL8AFDS5M:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/images/v2/menu-up.png   (ca22a1cb)
2017-08-24T12:43:17.4613791+08:00 0HL7AL8AFDS5N:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/js/menu.js   (ca22a1cb)
2017-08-24T12:43:17.4649670+08:00 0HL7AL8AFDS5M:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T12:43:17.4900548+08:00 0HL7AL8AFDS5M:00000003 [INF] User RequestPath：/images/v2/menu-up.png (c0a44d72)
2017-08-24T12:43:17.5040259+08:00 0HL7AL8AFDS5N:00000005 [INF] User IP:::1 (2144b813)
2017-08-24T12:43:17.5497669+08:00 0HL7AL8AFDS5N:00000005 [INF] User RequestPath：/menu/js/menu.js (aaba8f86)
2017-08-24T12:43:17.5509056+08:00 0HL7AL8AFDS5M:00000003 [INF] Request finished in 71.4928ms 404  (791a596a)
2017-08-24T12:43:17.5849947+08:00 0HL7AL8AFDS5N:00000005 [INF] Request finished in 100.3648ms 404  (791a596a)
2017-08-24T12:43:17.6267286+08:00 0HL7AL8AFDS5N:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T12:43:17.6339766+08:00 0HL7AL8AFDS5N:00000006 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T12:43:17.6426396+08:00 0HL7AL8AFDS5N:00000006 [INF] Request finished in 13.0573ms 200 image/x-icon (791a596a)
2017-08-24T12:48:48.9048800+08:00 0HL7ALDK3HM95:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T12:48:48.9648586+08:00 0HL7ALDK3HM95:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T12:48:48.9889365+08:00 0HL7ALDK3HM95:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T12:48:49.1298203+08:00 0HL7ALDK3HM95:00000001 [INF] Request finished in 256.9958ms 404  (791a596a)
2017-08-24T12:48:54.4328953+08:00 0HL7ALDK3HM95:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T12:48:54.4382194+08:00 0HL7ALDK3HM95:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T12:48:54.4629129+08:00 0HL7ALDK3HM95:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T12:48:54.5521972+08:00 0HL7ALDK3HM95:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:00:21.5662132+08:00 0HL7ALK2H1UC2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:00:21.6065865+08:00 0HL7ALK2H1UC2:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:00:21.6305190+08:00 0HL7ALK2H1UC2:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:00:21.7550437+08:00 0HL7ALK2H1UC2:00000001 [INF] Request finished in 217.727ms 404  (791a596a)
2017-08-24T13:00:43.5222762+08:00 0HL7ALK2H1UC2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/developer/register   (ca22a1cb)
2017-08-24T13:00:43.5479960+08:00 0HL7ALK2H1UC2:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T13:00:43.5725329+08:00 0HL7ALK2H1UC2:00000002 [INF] User RequestPath：/developer/register (62d232f1)
2017-08-24T13:00:43.5988536+08:00 0HL7ALK2H1UC2:00000002 [INF] Request finished in 57.4026ms 404  (791a596a)
2017-08-24T13:01:36.0309776+08:00 0HL7ALKO7PDT6:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:01:36.0830080+08:00 0HL7ALKO7PDT6:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:01:36.1078084+08:00 0HL7ALKO7PDT6:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:01:36.2360625+08:00 0HL7ALKO7PDT6:00000001 [INF] Request finished in 234.5967ms 404  (791a596a)
2017-08-24T13:01:56.4731637+08:00 0HL7ALKO7PDT6:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/Developer/Register   (ca22a1cb)
2017-08-24T13:01:56.4791029+08:00 0HL7ALKO7PDT6:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T13:01:56.5231677+08:00 0HL7ALKO7PDT6:00000002 [INF] User RequestPath：/Developer/Register (01d56035)
2017-08-24T13:01:56.5984531+08:00 0HL7ALKO7PDT6:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:01:56.6291468+08:00 0HL7ALKO7PDT6:00000002 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T13:01:56.6465331+08:00 0HL7ALKO7PDT6:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" in 66.5235ms (afa2e885)
2017-08-24T13:01:56.6725745+08:00 0HL7ALKO7PDT6:00000002 [INF] Request finished in 178.3408ms 200 text/plain; charset=utf-8 (791a596a)
2017-08-24T13:02:07.1660781+08:00 0HL7ALKO7PDT6:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T13:02:07.1908476+08:00 0HL7ALKO7PDT6:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T13:02:07.2161613+08:00 0HL7ALKO7PDT6:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T13:02:07.2258981+08:00 0HL7ALKO7PDT6:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:20:55.9756505+08:00 0HL7ALKO7PDTC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/Developer/Register   (ca22a1cb)
2017-08-24T13:20:56.0444734+08:00 0HL7ALKO7PDT6:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1128695.3161ms (afa2e885)
2017-08-24T13:20:56.0660332+08:00 0HL7ALKO7PDTC:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:20:56.0922425+08:00 0HL7ALKO7PDTC:00000001 [INF] User RequestPath：/Developer/Register (01d56035)
2017-08-24T13:20:56.1297014+08:00 0HL7ALKO7PDTC:00000001 [INF] Executing action method "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:20:56.1554604+08:00 0HL7ALKO7PDTC:00000001 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T13:20:56.1612997+08:00 0HL7ALKO7PDTC:00000001 [INF] Executed action "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" in 63.4164ms (afa2e885)
2017-08-24T13:20:56.1871846+08:00 0HL7ALKO7PDTC:00000001 [INF] Request finished in 190.5545ms 200 text/plain; charset=utf-8 (791a596a)
2017-08-24T13:20:56.2008360+08:00 0HL7ALKO7PDTC:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T13:20:56.2358503+08:00 0HL7ALKO7PDTC:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T13:20:56.2467824+08:00 0HL7ALKO7PDTC:00000002 [INF] Request finished in 47.5937ms 200 image/x-icon (791a596a)
2017-08-24T13:20:56.3244583+08:00 0HL7ALKO7PDT6:00000003 [ERR] Connection id ""0HL7ALKO7PDT6"", Request id ""0HL7ALKO7PDT6:00000003"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.ErrorJsonResultException: 微信请求发生错误！错误代码：40164，说明：invalid ip 116.52.7.139, not in whitelist hint: [A6zM0931e544]
   at Senparc.Weixin.HttpUtility.Get.GetJson[T](String url, Encoding encoding, Nullable`1 maxJsonLength)
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.GetToken(String appid, String secret, String grant_type)
   at Senparc.Weixin.MP.Containers.AccessTokenContainer.GetAccessTokenResult(String appId, Boolean getNewToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.Index() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T13:20:56.3287256+08:00 0HL7ALKO7PDT6:00000003 [INF] Request finished in 1129105.4026ms 0  (791a596a)
2017-08-24T13:20:58.9072183+08:00 0HL7ALKO7PDTC:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/Developer/Register   (ca22a1cb)
2017-08-24T13:20:58.9169560+08:00 0HL7ALKO7PDTC:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T13:20:58.9254919+08:00 0HL7ALKO7PDTC:00000003 [INF] User RequestPath：/Developer/Register (01d56035)
2017-08-24T13:20:58.9722381+08:00 0HL7ALKO7PDTC:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:20:58.9794274+08:00 0HL7ALKO7PDTC:00000003 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T13:20:58.9896891+08:00 0HL7ALKO7PDTC:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.DeveloperController.Register (Chris.Platform.WeChat)" in 54.6999ms (afa2e885)
2017-08-24T13:20:59.0008983+08:00 0HL7ALKO7PDTC:00000003 [INF] Request finished in 93.7012ms 200 text/plain; charset=utf-8 (791a596a)
2017-08-24T13:20:59.0119455+08:00 0HL7ALKO7PDTC:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T13:20:59.0371328+08:00 0HL7ALKO7PDTC:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T13:20:59.0632786+08:00 0HL7ALKO7PDTC:00000004 [INF] Request finished in 33.9484ms 200 image/x-icon (791a596a)
2017-08-24T13:21:05.4754324+08:00 0HL7ALKO7PDTC:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T13:21:05.4817981+08:00 0HL7ALKO7PDTC:00000005 [INF] User IP:::1 (2144b813)
2017-08-24T13:21:05.4900539+08:00 0HL7ALKO7PDTC:00000005 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T13:21:05.4955790+08:00 0HL7ALKO7PDTC:00000005 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:24:42.0477223+08:00 0HL7AM1LA6MG3:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:24:42.0885320+08:00 0HL7AM1LA6MG3:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:24:42.1119497+08:00 0HL7AM1LA6MG3:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:24:42.2662248+08:00 0HL7AM1LA6MG3:00000001 [INF] Request finished in 233.8923ms 404  (791a596a)
2017-08-24T13:24:52.2919758+08:00 0HL7AM1LA6MG3:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/wechat/index   (ca22a1cb)
2017-08-24T13:24:52.2994194+08:00 0HL7AM1LA6MG3:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T13:24:52.3249850+08:00 0HL7AM1LA6MG3:00000002 [INF] User RequestPath：/wechat/index (2894bff1)
2017-08-24T13:24:52.4835042+08:00 0HL7AM1LA6MG3:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.WeChatController.Get (Chris.Platform.WeChat)" with arguments (["Senparc.Weixin.MP.Entities.Request.PostModel", ""]) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:24:52.5415556+08:00 0HL7AM1LA6MG3:00000002 [ERR] 微信开发服务器认证失败 , requstParams:{"AppId":null,"Signature":null,"Msg_Signature":null,"Timestamp":null,"Nonce":null,"Token":null,"EncodingAESKey":null}! (f4570868)
2017-08-24T13:24:52.5495635+08:00 0HL7AM1LA6MG3:00000002 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T13:24:52.5744208+08:00 0HL7AM1LA6MG3:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.WeChatController.Get (Chris.Platform.WeChat)" in 128.3719ms (afa2e885)
2017-08-24T13:24:52.5998784+08:00 0HL7AM1LA6MG3:00000002 [INF] Request finished in 308.5651ms 200 text/plain; charset=utf-8 (791a596a)
2017-08-24T13:24:58.8484205+08:00 0HL7AM1LA6MG3:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T13:24:58.8536344+08:00 0HL7AM1LA6MG3:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T13:24:58.8818452+08:00 0HL7AM1LA6MG3:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T13:24:58.8973056+08:00 0HL7AM1LA6MG3:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:24:59.6621291+08:00 0HL7AM1LA6MG3:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 768.5441ms (afa2e885)
2017-08-24T13:24:59.8116920+08:00 0HL7AM1LA6MG3:00000003 [ERR] Connection id ""0HL7AM1LA6MG3"", Request id ""0HL7AM1LA6MG3:00000003"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [.axTtA0299sz10!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T13:24:59.8214061+08:00 0HL7AM1LA6MG3:00000003 [INF] Request finished in 969.1729ms 500  (791a596a)
2017-08-24T13:25:25.8784717+08:00 0HL7AM1LA6MG3:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T13:25:25.8895999+08:00 0HL7AM1LA6MG3:00000004 [INF] User IP:::1 (2144b813)
2017-08-24T13:25:25.9153851+08:00 0HL7AM1LA6MG3:00000004 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T13:25:25.9205021+08:00 0HL7AM1LA6MG3:00000004 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:26:05.0550339+08:00 0HL7AM1LA6MG3:00000004 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 39136.959ms (afa2e885)
2017-08-24T13:26:05.1551192+08:00 0HL7AM1LA6MG3:00000004 [ERR] Connection id ""0HL7AM1LA6MG3"", Request id ""0HL7AM1LA6MG3:00000004"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [6IQUJa0364sz10!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T13:26:05.1768184+08:00 0HL7AM1LA6MG3:00000004 [INF] Request finished in 39291.0185ms 500  (791a596a)
2017-08-24T13:26:05.1992669+08:00 0HL7AM1LA6MG3:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T13:26:05.2268756+08:00 0HL7AM1LA6MG3:00000005 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T13:26:05.2386162+08:00 0HL7AM1LA6MG3:00000005 [INF] Request finished in 35.0573ms 200 image/x-icon (791a596a)
2017-08-24T13:29:07.7781028+08:00 0HL7AM44VB16I:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:29:07.8156308+08:00 0HL7AM44VB16I:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:29:07.8198070+08:00 0HL7AM44VB16I:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:29:07.9376878+08:00 0HL7AM44VB16I:00000001 [INF] Request finished in 214.3279ms 404  (791a596a)
2017-08-24T13:29:18.3249214+08:00 0HL7AM44VB16I:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T13:29:18.3506969+08:00 0HL7AM44VB16I:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T13:29:18.3957800+08:00 0HL7AM44VB16I:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T13:29:18.4774979+08:00 0HL7AM44VB16I:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T13:56:46.2768563+08:00 0HL7AMJJ85FIV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:56:46.3237167+08:00 0HL7AMJJ85FIV:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:56:46.3329233+08:00 0HL7AMJJ85FIV:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:56:46.4669229+08:00 0HL7AMJJ85FIV:00000001 [INF] Request finished in 228.275ms 404  (791a596a)
2017-08-24T13:59:11.2658882+08:00 0HL7AMKUED6AQ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T13:59:11.3189705+08:00 0HL7AMKUED6AQ:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T13:59:11.3429483+08:00 0HL7AMKUED6AQ:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T13:59:11.4720072+08:00 0HL7AMKUED6AQ:00000001 [INF] Request finished in 260.3323ms 404  (791a596a)
2017-08-24T14:17:38.3803420+08:00 0HL7AMV8CMPS0:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:17:38.4174169+08:00 0HL7AMV8CMPS0:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:17:38.4227111+08:00 0HL7AMV8CMPS0:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:17:38.5660741+08:00 0HL7AMV8CMPS0:00000001 [INF] Request finished in 203.0701ms 404  (791a596a)
2017-08-24T14:17:49.5850998+08:00 0HL7AMV8CMPS0:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:17:49.6105512+08:00 0HL7AMV8CMPS0:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:17:49.6168147+08:00 0HL7AMV8CMPS0:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:17:49.7012239+08:00 0HL7AMV8CMPS0:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:19:41.7930833+08:00 0HL7AMV8CMPS0:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 112115.6728ms (afa2e885)
2017-08-24T14:19:41.9585853+08:00 0HL7AMV8CMPS0:00000002 [ERR] Connection id ""0HL7AMV8CMPS0"", Request id ""0HL7AMV8CMPS0:00000002"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [N8zH60581sz10!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:19:41.9796936+08:00 0HL7AMV8CMPS0:00000002 [INF] Request finished in 112380.8576ms 500  (791a596a)
2017-08-24T14:19:55.5316626+08:00 0HL7AMV8CMPS0:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:19:55.5389274+08:00 0HL7AMV8CMPS0:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T14:19:55.5638102+08:00 0HL7AMV8CMPS0:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:19:55.5910227+08:00 0HL7AMV8CMPS0:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:20:18.2844141+08:00 0HL7AMV8CMPS0:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 22715.8507ms (afa2e885)
2017-08-24T14:20:18.3612599+08:00 0HL7AMV8CMPS0:00000003 [ERR] Connection id ""0HL7AMV8CMPS0"", Request id ""0HL7AMV8CMPS0:00000003"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [T._Aea0618sz12!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:20:18.3671495+08:00 0HL7AMV8CMPS0:00000003 [INF] Request finished in 22843.9236ms 500  (791a596a)
2017-08-24T14:20:18.4105223+08:00 0HL7AMV8CMPS0:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T14:20:18.4155494+08:00 0HL7AMV8CMPS0:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T14:20:18.4256065+08:00 0HL7AMV8CMPS0:00000004 [INF] Request finished in 35.2888ms 200 image/x-icon (791a596a)
2017-08-24T14:26:44.8471100+08:00 0HL7AN4B8QPKV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:26:44.8929232+08:00 0HL7AN4B8QPKV:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:26:44.9003831+08:00 0HL7AN4B8QPKV:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:26:45.0895358+08:00 0HL7AN4B8QPKV:00000001 [INF] Request finished in 250.9127ms 404  (791a596a)
2017-08-24T14:26:52.5547366+08:00 0HL7AN4B8QPKV:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:26:52.5607653+08:00 0HL7AN4B8QPKV:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:26:52.5888279+08:00 0HL7AN4B8QPKV:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:26:52.6705841+08:00 0HL7AN4B8QPKV:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:26:53.7359517+08:00 0HL7AN4B8QPKV:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 1085.319ms (afa2e885)
2017-08-24T14:26:53.8869496+08:00 0HL7AN4B8QPKV:00000002 [ERR] Connection id ""0HL7AN4B8QPKV"", Request id ""0HL7AN4B8QPKV:00000002"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [NWOkHA0013sz12!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:26:53.8972214+08:00 0HL7AN4B8QPKV:00000002 [INF] Request finished in 1339.3025ms 500  (791a596a)
2017-08-24T14:27:37.9481741+08:00 0HL7AN4R2NDVE:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:27:37.9873504+08:00 0HL7AN4R2NDVE:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:27:37.9983002+08:00 0HL7AN4R2NDVE:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:27:38.2431363+08:00 0HL7AN4R2NDVE:00000001 [INF] Request finished in 313.3389ms 404  (791a596a)
2017-08-24T14:28:17.6916589+08:00 0HL7AN4R2NDVE:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:28:17.6967332+08:00 0HL7AN4R2NDVE:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:28:17.7231484+08:00 0HL7AN4R2NDVE:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:28:17.8094982+08:00 0HL7AN4R2NDVE:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:34:08.9042249+08:00 0HL7AN8FJOO3N:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:34:08.9407337+08:00 0HL7AN8FJOO3N:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:34:08.9464368+08:00 0HL7AN8FJOO3N:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:34:09.0874871+08:00 0HL7AN8FJOO3N:00000001 [INF] Request finished in 212.3941ms 404  (791a596a)
2017-08-24T14:34:16.6327375+08:00 0HL7AN8FJOO3N:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:34:16.6388189+08:00 0HL7AN8FJOO3N:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:34:16.6638470+08:00 0HL7AN8FJOO3N:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:34:16.7495658+08:00 0HL7AN8FJOO3N:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:34:34.9882500+08:00 0HL7AN8FJOO3N:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 18261.1274ms (afa2e885)
2017-08-24T14:34:35.1318397+08:00 0HL7AN8FJOO3N:00000002 [ERR] Connection id ""0HL7AN8FJOO3N"", Request id ""0HL7AN8FJOO3N:00000002"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [C0trCa0474sz12!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:34:35.1496417+08:00 0HL7AN8FJOO3N:00000002 [INF] Request finished in 18525.4148ms 500  (791a596a)
2017-08-24T14:35:09.4221349+08:00 0HL7AN8FJOO3N:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:35:09.4487537+08:00 0HL7AN8FJOO3N:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T14:35:09.4743116+08:00 0HL7AN8FJOO3N:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:35:09.4799912+08:00 0HL7AN8FJOO3N:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:35:37.4769744+08:00 0HL7AN8FJOO3N:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 27996.212ms (afa2e885)
2017-08-24T14:35:37.5611353+08:00 0HL7AN8FJOO3N:00000003 [ERR] Connection id ""0HL7AN8FJOO3N"", Request id ""0HL7AN8FJOO3N:00000003"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [b8zg_0537sz12!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:35:37.5806643+08:00 0HL7AN8FJOO3N:00000003 [INF] Request finished in 28154.2323ms 500  (791a596a)
2017-08-24T14:35:37.6069911+08:00 0HL7AN8FJOO3N:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T14:35:37.6332504+08:00 0HL7AN8FJOO3N:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T14:35:37.6512283+08:00 0HL7AN8FJOO3N:00000004 [INF] Request finished in 39.9124ms 200 image/x-icon (791a596a)
2017-08-24T14:39:36.8515835+08:00 0HL7ANBGN5GUU:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:39:36.8917483+08:00 0HL7ANBGN5GUU:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:39:36.9153142+08:00 0HL7ANBGN5GUU:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:39:37.0719504+08:00 0HL7ANBGN5GUU:00000001 [INF] Request finished in 248.0181ms 404  (791a596a)
2017-08-24T14:39:42.3993177+08:00 0HL7ANBGN5GUU:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:39:42.4250379+08:00 0HL7ANBGN5GUU:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:39:42.4490695+08:00 0HL7ANBGN5GUU:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:39:42.5400106+08:00 0HL7ANBGN5GUU:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:41:20.8572834+08:00 0HL7ANCFR871T:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T14:41:20.9017482+08:00 0HL7ANCFR871T:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T14:41:20.9268167+08:00 0HL7ANCFR871T:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T14:41:21.0830214+08:00 0HL7ANCFR871T:00000001 [INF] Request finished in 238.1598ms 404  (791a596a)
2017-08-24T14:41:26.5654832+08:00 0HL7ANCFR871T:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:41:26.5912059+08:00 0HL7ANCFR871T:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T14:41:26.5986366+08:00 0HL7ANCFR871T:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:41:26.6825773+08:00 0HL7ANCFR871T:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:41:41.9411232+08:00 0HL7ANCFR871T:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 15283.3883ms (afa2e885)
2017-08-24T14:41:42.0850836+08:00 0HL7ANCFR871T:00000002 [ERR] Connection id ""0HL7ANCFR871T"", Request id ""0HL7ANCFR871T:00000002"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [IZPieA0901sz10!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:41:42.0909977+08:00 0HL7ANCFR871T:00000002 [INF] Request finished in 15528.7006ms 500  (791a596a)
2017-08-24T14:44:07.8551941+08:00 0HL7ANCFR871T:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T14:44:07.8614031+08:00 0HL7ANCFR871T:00000003 [INF] User IP:::1 (2144b813)
2017-08-24T14:44:07.8866189+08:00 0HL7ANCFR871T:00000003 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T14:44:07.8954066+08:00 0HL7ANCFR871T:00000003 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T14:44:18.2499115+08:00 0HL7ANCFR871T:00000003 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 10358.0305ms (afa2e885)
2017-08-24T14:44:18.3348934+08:00 0HL7ANCFR871T:00000003 [ERR] Connection id ""0HL7ANCFR871T"", Request id ""0HL7ANCFR871T:00000003"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [NlAYfa0058sz10!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T14:44:18.3506270+08:00 0HL7ANCFR871T:00000003 [INF] Request finished in 10506.2917ms 500  (791a596a)
2017-08-24T14:44:18.3740361+08:00 0HL7ANCFR871T:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T14:44:18.4007533+08:00 0HL7ANCFR871T:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T14:44:18.4130681+08:00 0HL7ANCFR871T:00000004 [INF] Request finished in 38.6026ms 200 image/x-icon (791a596a)
2017-08-24T15:00:26.5082151+08:00 0HL7ANN4S6OV2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T15:00:26.5735169+08:00 0HL7ANN4S6OV2:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T15:00:26.5799093+08:00 0HL7ANN4S6OV2:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T15:00:26.7432254+08:00 0HL7ANN4S6OV2:00000001 [INF] Request finished in 251.3189ms 404  (791a596a)
2017-08-24T15:04:41.2319880+08:00 0HL7ANN4S6OV3:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T15:04:41.2760914+08:00 0HL7ANN4S6OV3:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T15:04:41.3203643+08:00 0HL7ANN4S6OV3:00000001 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T15:04:41.4389701+08:00 0HL7ANN4S6OV3:00000001 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T15:04:52.6255866+08:00 0HL7ANN4S6OV3:00000001 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 11210.699ms (afa2e885)
2017-08-24T15:04:52.8576902+08:00 0HL7ANN4S6OV3:00000001 [ERR] Connection id ""0HL7ANN4S6OV3"", Request id ""0HL7ANN4S6OV3:00000001"": An unhandled exception was thrown by the application. (560e7d32)
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.<ConnectAsync>d__72.MoveNext() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 799
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<ConnectAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAndRefreshAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.<GetStringAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chris.Platform.WeChat.Services.WeChatServices.<GetToken>d__5.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Services\WeChatServices.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T15:04:52.8640921+08:00 0HL7ANN4S6OV3:00000001 [INF] Request finished in 11651.9717ms 500  (791a596a)
2017-08-24T15:05:35.9658713+08:00 0HL7ANN4S6OV3:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/menu/index   (ca22a1cb)
2017-08-24T15:05:35.9908642+08:00 0HL7ANN4S6OV3:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T15:05:36.0352184+08:00 0HL7ANN4S6OV3:00000002 [INF] User RequestPath：/menu/index (82342c44)
2017-08-24T15:05:36.0410186+08:00 0HL7ANN4S6OV3:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T15:06:10.6617071+08:00 0HL7ANN4S6OV3:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.MenuController.Index (Chris.Platform.WeChat)" in 34618.7157ms (afa2e885)
2017-08-24T15:06:10.7659582+08:00 0HL7ANN4S6OV3:00000002 [ERR] Connection id ""0HL7ANN4S6OV3"", Request id ""0HL7ANN4S6OV3:00000002"": An unhandled exception was thrown by the application. (560e7d32)
Senparc.Weixin.Exceptions.WeixinMenuException: api unauthorized hint: [jkpmea0370sz12!]
   at Senparc.Weixin.MP.CommonAPIs.CommonApi.<>c.<GetMenu>b__19_0(String accessToken)
   at Senparc.Weixin.CommonAPIs.ApiHandlerWapper.ApiHandlerWapperBase.TryCommonApiBase[T](PlatformType platformType, Func`1 accessTokenContainer_GetFirstOrDefaultAppIdFunc, Func`2 accessTokenContainer_CheckRegisteredFunc, Func`3 accessTokenContainer_GetAccessTokenResultFunc, Int32 invalidCredentialValue, Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Senparc.Weixin.MP.ApiHandlerWapper.TryCommonApi[T](Func`2 fun, String accessTokenOrAppId, Boolean retryIfFaild)
   at Chris.Platform.WeChat.Controllers.MenuController.<Index>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Controllers\MenuController.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chris.Platform.WeChat.Models.Middleware.RecordRequestInfoMiddleware.<Invoke>d__3.MoveNext() in D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\Models\Middleware\RecordRequestInfoMiddleware.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2017-08-24T15:06:10.7919849+08:00 0HL7ANN4S6OV3:00000002 [INF] Request finished in 34804.06ms 500  (791a596a)
2017-08-24T16:40:02.0544675+08:00 0HL7APEQ8P7SQ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:40:02.1645177+08:00 0HL7APEQ8P7SQ:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T16:40:02.1693216+08:00 0HL7APEQ8P7SQ:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:40:02.4637023+08:00 0HL7APEQ8P7SQ:00000001 [INF] Request finished in 485.4384ms 404  (791a596a)
2017-08-24T16:40:56.2286684+08:00 0HL7APFANUCGE:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:40:56.2902089+08:00 0HL7APFANUCGE:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T16:40:56.2943938+08:00 0HL7APFANUCGE:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:40:56.4356453+08:00 0HL7APFANUCGE:00000001 [INF] Request finished in 242.9114ms 404  (791a596a)
2017-08-24T16:41:17.3395812+08:00 0HL7APFANUCGE:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/home/index   (ca22a1cb)
2017-08-24T16:41:17.3659915+08:00 0HL7APFANUCGE:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T16:41:17.3716444+08:00 0HL7APFANUCGE:00000002 [INF] User RequestPath：/home/index (fb6698ed)
2017-08-24T16:41:17.4516629+08:00 0HL7APFANUCGE:00000002 [INF] Executing action method "Chris.Platform.WeChat.Controllers.HomeController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T16:41:17.4624312+08:00 0HL7APFANUCGE:00000002 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T16:41:17.4841660+08:00 0HL7APFANUCGE:00000002 [INF] Executed action "Chris.Platform.WeChat.Controllers.HomeController.Index (Chris.Platform.WeChat)" in 38.4106ms (afa2e885)
2017-08-24T16:41:17.5097536+08:00 0HL7APFANUCGE:00000002 [INF] Request finished in 149.7932ms 200 text/plain; charset=utf-8 (791a596a)
2017-08-24T16:42:51.4747866+08:00 0HL7APGD3C1N5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:42:51.5332201+08:00 0HL7APGD3C1N5:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T16:42:51.5580542+08:00 0HL7APGD3C1N5:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:42:51.7066913+08:00 0HL7APGD3C1N5:00000001 [INF] Request finished in 250.5292ms 404  (791a596a)
2017-08-24T16:43:05.9114509+08:00 0HL7APGD3C1N5:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:43:05.9165468+08:00 0HL7APGD3C1N5:00000002 [INF] User IP:::1 (2144b813)
2017-08-24T16:43:05.9417396+08:00 0HL7APGD3C1N5:00000002 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:43:05.9683854+08:00 0HL7APGD3C1N5:00000002 [INF] Request finished in 36.2302ms 404  (791a596a)
2017-08-24T16:43:05.9762932+08:00 0HL7APGD3C1N5:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T16:43:05.9839393+08:00 0HL7APGD3C1N5:00000003 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T16:43:05.9938386+08:00 0HL7APGD3C1N5:00000003 [INF] Request finished in 17.2999ms 200 image/x-icon (791a596a)
2017-08-24T16:43:07.2297589+08:00 0HL7APGD3C1N5:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:43:07.2348997+08:00 0HL7APGD3C1N5:00000004 [INF] User IP:::1 (2144b813)
2017-08-24T16:43:07.2598863+08:00 0HL7APGD3C1N5:00000004 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:43:07.2875004+08:00 0HL7APGD3C1N5:00000004 [INF] Request finished in 36.0408ms 404  (791a596a)
2017-08-24T16:43:07.3138532+08:00 0HL7APGD3C1N5:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52141/favicon.ico   (ca22a1cb)
2017-08-24T16:43:07.3386043+08:00 0HL7APGD3C1N5:00000005 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\WorkSpaces\Chris\Group.WeChat\Chris.Platform.WeChat\Chris.Platform.WeChat\wwwroot\favicon.ico"' (27b0a520)
2017-08-24T16:43:07.3468873+08:00 0HL7APGD3C1N5:00000005 [INF] Request finished in 29.2742ms 200 image/x-icon (791a596a)
2017-08-24T16:43:38.1712294+08:00 0HL7APGR0NQTG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/   (ca22a1cb)
2017-08-24T16:43:38.2141966+08:00 0HL7APGR0NQTG:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T16:43:38.2379673+08:00 0HL7APGR0NQTG:00000001 [INF] User RequestPath：/ (2d52e501)
2017-08-24T16:43:38.4079523+08:00 0HL7APGR0NQTG:00000001 [INF] Request finished in 260.0634ms 404  (791a596a)
2017-08-24T16:43:49.8512192+08:00 0HL7APGR0NQTH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52141/home/index   (ca22a1cb)
2017-08-24T16:43:49.8765894+08:00 0HL7APGR0NQTH:00000001 [INF] User IP:::1 (2144b813)
2017-08-24T16:43:49.9012352+08:00 0HL7APGR0NQTH:00000001 [INF] User RequestPath：/home/index (fb6698ed)
2017-08-24T16:43:49.9634979+08:00 0HL7APGR0NQTH:00000001 [INF] Executing action method "Chris.Platform.WeChat.Controllers.HomeController.Index (Chris.Platform.WeChat)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-08-24T16:43:49.9922783+08:00 0HL7APGR0NQTH:00000001 [INF] Executing ContentResult with HTTP Response ContentType of "text/plain; charset=utf-8" (7ec2a4e9)
2017-08-24T16:43:50.0118232+08:00 0HL7APGR0NQTH:00000001 [INF] Executed action "Chris.Platform.WeChat.Controllers.HomeController.Index (Chris.Platform.WeChat)" in 52.4195ms (afa2e885)
2017-08-24T16:43:50.0380622+08:00 0HL7APGR0NQTH:00000001 [INF] Request finished in 166.0994ms 200 text/plain; charset=utf-8 (791a596a)
